{% set name = "ovh" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ovh-{{ version }}.tar.gz
  sha256: 61aaf1eb2992fd5af819ba5add08266e9ede2e002451e3a1606a4c367ddaa04f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=30.3.0
  run:
    - python >=3.6
    - requests >=2.11.0

test:
  imports:
    - ovh
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://api.ovh.com
  summary: '"Official module to perform HTTP requests to the OVHcloud APIs"'
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/ovh/python-ovh

extra:
  recipe-maintainers:
    - BastianZim
