{% set name = "ovh" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ovh-{{ version }}.tar.gz
  sha256: d311f08ec17b62cc61216b3dacf03ee89f95a1da9036a595dac29fc9d798b827

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=30.3.0
  run:
    - requests-oauthlib >=2.0.0
    - python >=3.6
    - requests >=2.31.0

test:
  imports:
    - ovh
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://api.ovh.com
  summary: '"Official module to perform HTTP requests to the OVHcloud APIs"'
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/ovh/python-ovh

extra:
  recipe-maintainers:
    - BastianZim
